---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    validatepodresources: "yes"
  creationTimestamp: null
  name: test-ns-validate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reversewords-burstable
  name: reversewords-burstable
  namespace: test-ns-validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reversewords-burstable
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reversewords-burstable
    spec:
      containers:
      - image: quay.io/mavazque/trbsht:latest
        name: reversewords-burstable
        resources: 
          requests:
            cpu: 10
            memory: "250M"
          limits:
            cpu: 20
            memory: "500M"
status: {}
