---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    onepodatatime: "yes"
  creationTimestamp: null
  name: test-ns-onepodatatime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reversewords
  name: reversewords
  namespace: test-ns-onepodatatime
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reversewords
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reversewords
    spec:
      containers:
      - image: quay.io/mavazque/reversewords:latest
        name: reversewords
        resources: {}
status: {}
