---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: one-pod-at-a-time
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: wh-one-pod-at-a-time-serving-cert
  name: wh-one-pod-at-a-time
  namespace: one-pod-at-a-time
  labels:
    app: wh-one-pod-at-a-time
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: wh-one-pod-at-a-time
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wh-one-pod-at-a-time
  namespace: one-pod-at-a-time
  labels:
    app: wh-one-pod-at-a-time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wh-one-pod-at-a-time
  template:
    metadata:
      name: wh-one-pod-at-a-time
      labels:
        app: wh-one-pod-at-a-time
    spec:
      containers:
        - name: webhook
          image: quay.io/mavazque/onepodatatime:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 8443
              scheme: HTTPS
          volumeMounts:
          - mountPath: /go/src/github.com/mvazquezc/k8s-mutate-webhook/ssl/
            name: serving-cert
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: wh-one-pod-at-a-time-serving-cert
